spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: dev@sagitta
    password: password@sagitta

  data:
    redis:
      port: 6379
      password:
      timeout: 600ms

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 300000

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8083
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /authenticate/$\{segment}
        - id: user-service
          uri: http://localhost:8084
          metadata:
            public: false
            docs: /api/docs
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/?(?<segment>.*), /users/$\{segment}
        - id: tax-service
          uri: http://localhost:8082
          metadata:
            public: false
            docs: /api/docs
          predicates:
            - Path=/api/tax/**
          filters:
            - RewritePath=/api/tax/?(?<segment>.*), /tax/$\{segment}

    config:
      enabled: false

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"


#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#
#logging:
#  config: classpath:log/logback-dev.xml
#
#loki:
#  distributor:
#    url: http://localhost:3100/loki/api/v1/push
