spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: dev@sagitta
    password: password@sagitta

  data:
    redis:
      port: 6379
      password:
      timeout: 600ms

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 300000

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${hosts.userservice}:8081
          metadata:
            docs: /api/docs
          predicates:
            - Path=/api/user-management/**
          filters:
            - RewritePath=/api/user-management/?(?<segment>.*), /api/user/$\{segment}
        # FIXME: Make sure that only external clients can access /authenticate
        - id: authentication-service
          uri: http://${hosts.auth-service}:8082
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/authenticate/**
        - id: tax-service
          uri: http://${hosts.tax-service}:8082
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/authenticate/**
    config:
      enabled: false

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"


#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
#
#logging:
#  config: classpath:log/logback-dev.xml
#
#loki:
#  distributor:
#    url: http://localhost:3100/loki/api/v1/push
